server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        # Auth Service
        - id: auth-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/auth/**

        # Product Service
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products/**

        # Cart Service
        - id: cart-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/cart/**

        # AI Service
        - id: ai-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/ai/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

security:
  jwt:
    secret: ${JWT_SECRET:YOUR_SAME_JWT_SECRET_AS_AUTH_SERVICE}
    issuer: ${JWT_ISSUER:auth-service}